python main.py --gpus "2," --max_epochs=8  --num_workers=32 \
   --model_name_or_path  bert-base-uncased \
   --accumulate_grad_batches 1 \
   --model_class BertKGC \
   --batch_size 64 \
   --checkpoint ${yourcheckpoint} \
   --litmodel_class GetEntityEmbeddingLitModel \
   --pretrain 1 \
   --bce 0 \
   --check_val_every_n_epoch 1 \
   --overwrite_cache \
   --data_dir dataset/WN18RR_ind \
   --eval_batch_size 256 \
   --wandb \
   --max_seq_length 64 \
   --lr 3e-5